ConfigVersion: Not Used Yet
## If Set To True The Plugin Will Automatically Update The Plugin When A New Update Is Published On Bukkit
AutoUpdate: true
## If Set To True The Plugin Will Send Usage Information To mcstats.org So That I Can See Who Is Using It
Metrics: true
## This Limit Only Affects Players With The VIP Perm, Admins Will Be Able To Exceed This Limit (Includes The /Home One)
HomesLimit: 3